apiVersion: v1
appVersion: 2.249.3
description: Jenkins - Build great things at any scale! The leading open source automation
  server, Jenkins provides hundreds of plugins to support building, deploying and
  automating any project.
home: https://jenkins.io/
icon: https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png
maintainers:
- email: maor.friedman@redhat.com
  name: maorfr
- email: mail@torstenwalter.de
  name: torstenwalter
- email: garridomota@gmail.com
  name: mogaal
- email: wmcdona89@gmail.com
  name: wmcdona89
- email: timjacomb1@gmail.com
  name: timja
name: jenkins
sources:
- https://github.com/jenkinsci/jenkins
- https://github.com/jenkinsci/docker-inbound-agent
- https://github.com/maorfr/kube-tasks
- https://github.com/jenkinsci/configuration-as-code-plugin
version: 2.19.0