apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
{{ include "waypoint.labels" . | indent 4 }}
  name: {{ include "waypoint.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "waypoint.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: waypoint-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "waypoint.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - args:
        - server
        - run
        - -vvv
        - -db=/data/data.db
        - -accept-tos
        - -listen-grpc=0.0.0.0:9701
        - -listen-http=0.0.0.0:9702
        - -advertise-addr={{ .Values.waypointGrpc.ingress.hosts }}:{{ .Values.service.waypointGrpcPort }} 
        - -advertise-tls=true
        - -advertise-tls-skip-verify=true
        command:
        - waypoint
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: WAYPOINT_SERVER_ADDR
          value: waypoint.fuchicorp.com
          
        livenessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTPS
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 9701
          name: grpc
          protocol: TCP
        - containerPort: 9702
          name: http
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        {{- toYaml .Values.waypointServer.securityContext | nindent 8 }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem