apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init-job
  namespace: tools
spec:
  template:
    spec:
      containers:
      - name: vault-init-job
        image: vault:1.4.0
        command: ['/bin/sh', '-c', 'sh /init/init.sh' ]
        volumeMounts:
        - name: vault-data
          mountPath: "/init"
      serviceAccount: common-service-account
      restartPolicy: OnFailure
      volumes:
      - name: vault-data
        configMap:
          name: vault-init-cm
  backoffLimit: 10
  activeDeadlineSeconds: 360